Orders monitoring
vladkash/optorgkz pull request #21
Opened 2022-09-23 10:37 UTC by odonata95

2022-09-24 13:38 UTC, vladkash reviewed
В целом хорошо, в основном мелкие замечания про магические строки, дублирование кода

2022-09-24 13:38 UTC, vladkash commented on app/Http/Controllers/BotManController.php
> +        ];
Вынесите, пожалуйста, в отдельный конфиг файл botman.php

2022-09-24 13:38 UTC, vladkash commented on app/Http/Controllers/BotManController.php
> +                        $order_product->status = 'gathering';
вынесите в константу и заиспользуйте здесь

2022-09-24 13:38 UTC, vladkash commented on app/Http/Controllers/BotManController.php
> +                    if ($action == 'gathering') {
Все действия тоже хочется видеть не волшебными строками, а вынесеными в константы

2022-09-24 13:38 UTC, vladkash commented on app/Http/Controllers/BotManController.php
> +                    } elseif ($action == 'new_price') {
Заменить на константу

2022-09-24 13:38 UTC, vladkash commented on app/Http/Controllers/BotManController.php
> +                    } elseif ($action == 'replacement') {
заменить на константу

2022-09-24 13:38 UTC, vladkash commented on database/migrations/2022_09_20_173434_order_product_add_status_column.php
> +            $table->enum('status', ['out_of_stock', 'new_price', 'gathering', 'replacement', 'sent'])->nullable();
тут тоже хорош бы константы использовать из модели OrderProduct на каждый статус

2022-09-24 13:38 UTC, vladkash commented on app/Botman/ReplacementOrderProductConversation.php
> +                $replacements = json_decode($this->order_product->replacements, true);
лучше добавить в casts модели 'replacements' => 'json', тогда эти преобразования не понадобятся

2022-09-24 13:38 UTC, vladkash commented on app/Botman/ReplacementOrderProductConversation.php
> +                $this->order_product->replacements = json_encode($replacements);
лучше добавить в casts модели 'replacements' => 'json', тогда эти преобразования не понадобятся

2022-09-24 13:38 UTC, vladkash commented on app/Models/OrderStatus.php
> +    protected $fillable = [
наверное, тут guarded должен быть

2022-09-24 13:38 UTC, vladkash commented on app/Models/OrderStatus.php
> +    public $process_statuses = [1, 2, 15];
давайте сделаем статичной константой

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +        }
```suggestion
        $filter_model = $request->get('filter_model', '');;
```

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +        }
```suggestion
        $filter_excluded_products = $request->get('filter_excluded_products', []);
```

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +        }
```suggestion
        $order_products = $order_products = $request->get('order_products', []);
        $order = Order::query()->findOrFail($order_id);
```

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +        if ($order) {
вы используете при поиске товара метод findOrFail, поэтому он либо будет найден, либо вылетит 404 ошибка, эта проверка не нужна

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                    'order_product_id' => $order_product['order_product_id'] ?? 0
а это точно хорошая идея использовать здесь какой-то фейковый идентификатор 0? может можно какой-нибудь валидацией лучше гарантировать, что будет нужное поле в $order_product?

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +        if ($order) {
проверка не нужна

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +            $botman->setDriver(DriverManager::loadFromName(TelegramDriver::class, $config));
тут уже явно видно дублирования, кроме выноса конфига в отдельный файл создание экземпляра ботмана тоже надо вынести, я бы вообще закинул его как синглтон в контейнер DI

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                            $message_text .= "\n<b>" . $product_atribute['attribute_description']['name'] . "</b> " . $product_atribute['text'];
я для этого куска предлагаю создать blade template, в котором это все будет красиво выглядеть, прокинуть в него переменные и получить уже готовый текст

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                        Button::create('Изменить цену закупки')->value('order_product:' . $order_product->order_product_id . ';action:new_price'),
тут в action:... использовать созданные константы для них

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                    $order_product->telegram_message_id = $result['result']['message_id'] ?? 0;
кажется, что апи телеграм гарантирует, что будет нужный айдишник при успешно ответе, а если вы запишете каким-то образом ноль и потом отправите его в reply_to_message_id или в запрос на редактирование/удаление, то скорее всего код упадет, поэтому записи нуля лучше избежать

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                    $order_product->status = 'sent';
заменить на вынесенную константу

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +                            <b v-if="order_product.status === 'sent'" class="font-bold">Sent</b>
я думаю для этих вариантов лучше сделать switch case в отдельном методе, чтобы получить только надпись, а не дублировать шаблон несколько раз

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +        this.currency_rate = Nova.config.app_config.currency_rate;
:+1:

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +        productsQueryExcluded: []
давайте мы для неинициализированных значений строк и цифр будем лучше null использовать, чтобы точно не было шанса какому-то условию сработать при сравнении через ===, да и семантически поприятнее

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +            return this.formatPriceValue(total).replace(/(?<!\..*)(\d)(?=(?:\d{3})+(?:\.|$))/g, '$1 ');
это регулярное выражение не один раз встречается в файле, вынесите, пожалуйста, в data

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +        cancelOrderEdit(order_id) {
параметр order_id не используется, можно убрать

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +                    this.orderOnSave = 0;
используйте null

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +                    this.orderOnSent = 0;
используйте null

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +            <card v-for="order in orders" class="flex-1 w-full p-3 pt-6 pb-6 m-2">
давайте пропишем [key](https://vuejs.org/guide/essentials/list.html#maintaining-state-with-key), order.order_id

2022-09-24 13:38 UTC, vladkash commented on nova-components/Orders/resources/js/components/Tool.vue
> +                    <tr v-for="(order_product, index) in order.order_products">
давайте пропишем [key](https://vuejs.org/guide/essentials/list.html#maintaining-state-with-key), order_product_id

2022-09-26 09:00 UTC, odonata95 commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                    'order_product_id' => $order_product['order_product_id'] ?? 0
так нужно, если есть значение то обновляем, если 0 то создает новий

2022-09-26 09:18 UTC, odonata95 commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                            $message_text .= "\n<b>" . $product_atribute['attribute_description']['name'] . "</b> " . $product_atribute['text'];
нет смисла так как здесь нет верстки, толька текст с виделением bold
немного подправлю чтоб здесь красивее било

2022-09-26 09:39 UTC, odonata95 commented on nova-components/Orders/resources/js/components/Tool.vue
> +            return this.formatPriceValue(total).replace(/(?<!\..*)(\d)(?=(?:\d{3})+(?:\.|$))/g, '$1 ');
винес в функцию дополнительним параметром

2022-09-27 14:58 UTC, vladkash commented on nova-components/Orders/src/Http/Controllers/OrdersController.php
> +                            $message_text .= "\n<b>" . $product_atribute['attribute_description']['name'] . "</b> " . $product_atribute['text'];
@odonata95 смысл как раз очень даже есть, потому что редактировать текст этого сообщения через blade template будет гораздо легче, не будет этих страшных конкатенаций, можно будет использовать if и for в шаблоне. Сделайте это, пожалуйста

2022-09-27 14:59 UTC, vladkash requested changes
Все ок, вынесите только текст сообщения в template, пожалуйста, я сделал unresolve

2022-09-27 16:06 UTC, vladkash approved these changes

2022-10-01 12:52 UTC, merged